### ISSUE TITLE
Songs display backwards on app. 

### ISSUE THREAD

**Issue by ProtoChoco** [apognu/otter#25]
When you view an album, the tracklist is reversed and it puts it in the queue backwards.

**Comment by delcake** [comment]
Wanted to say I'm experiencing this as well. Particularly, the app seems to be displaying album track order by creation time in descending order instead of respecting track numbers.

**Comment by apognu** [comment]
Hi,

I'm really sorry about the delay. Some unforeseen personal issues have prevented from being more active here.

This should be fixed in version 1.0.16 that is currently being deployed on the app store (or available as an APK in the release section).

Please do not hesitate to reopen if you notice this is not fixed.
