### ISSUE TITLE
Use translation system (e.g. Funkwhale's Weblate instance)

### ISSUE THREAD

**Issue by keunes** [apognu/otter#41]
If I noticed correctly, no translation system is currently used. Using Weblate for example would make it easier for others to translate. Given the link with Funkwhale, I'm sure its translators would be happy to work on Otter as well.

Using Funkwhale's instance would also help create consistency among the two projects.

**Comment by apognu** [comment]
I'm all for it, if it helps manage translations (I only speak English and French). As far I as can see, Weblate does handle commiting changes as PRs, which is mandatory, since I will not give write access to this repo.

One last detail (maybe you know), as mentionned in https://github.com/apognu/otter/pull/38, I need to check which strategy is used by the tool for missing translations. Android will not let me build and publish the app if some string translations are missing, which could be quite blocking if I need to wait for someone to translate something before being able to publish a release.

Any information about Weblate is welcome (I'm reading the docs right now).

As for Funkwhale's instance, that would really be good. I'd need to contact a core team member to see if that could be arranged (but let's keep in mind this is in no way an official project, so there might be some issues with hosting Otter's translations there).

**Comment by apognu** [comment]
Apparently, I was mistaken. Android does not prevent compilation when strings are missing, it only throws warnings. This is not as blocking as I originally thought.

**Comment by keunes** [comment]
> I'd need to contact a core team member to see if that could be arranged (but let's keep in mind this is in no way an official project, so there might be some issues with hosting Otter's translations there).

There's also another, completely unrelated project (Tab Center Reborn) [hosted on the instance](https://translate.funkwhale.audio/projects/) - I'm pretty sure a strongly linked project wouldn't be a problem. You know how to get in touch? Funkwhale's initiator currently is on holiday if I'm not mistaken. But you might take your luck in https://riot.im/app/#/room/#funkwhale-dev:matrix.org?

**Comment by apognu** [comment]
Yes, Agate put me in touch with someone that could help me out while she's away. I'll try to reach out to see if anything can be done.

**Comment by apognu** [comment]
Apparently, it was approved.

I will still need some time for them to give me access and for me to configure and test it, but we are making progress.

**Comment by apognu** [comment]
Otter was added to [Funkwhale's Weblate instance](https://translate.funkwhale.audio/projects/otter/android/). I'll update Otter's README with this.

Everything seems to work properly but it may be a bit muddled until I get familiar with the whole system.

I'll close this. If anyone has any suggestion, please respond and I'll reopen.

**Comment by keunes** [comment]
That's great, thanks Antoine! Created some 'issues' for some of the strings that I think could be improved (or are unclear to me).

**Comment by apognu** [comment]
I applied most of your suggestions and answered a few of your comments.

I had planned to add (at least some) context screenshots this weekend, so everything should be clearer after that. Thank you for helping out.
