### ISSUE TITLE
Change the sorting order for artists and albums

### ISSUE THREAD

**Issue by apognu** [apognu/otter#54]
Artists and albums are currently sorted following the returned order from Funkwhale's API. It has been reported on Matrix as not being the most natural and somehow confusing.

Here are the candidates for sorting:
 * Global artists and albums: alphabetical
 * Artist's albums : _alphabetical or by release date_

Release date sorting for albums could still be confusing for the user if we do not show the release date somewhere, I will try and see how I can insert it into the UI without making it too heavy.

**Comment by apognu** [comment]
Here is an attempt at displaying and sorting the albums by release date:

<img src="https://user-images.githubusercontent.com/3017182/86911739-51d5f980-c10b-11ea-8f0e-96f9edb26439.jpg" width="400" />

Any thought?

**Comment by keunes** [comment]
> following the returned order from Funkwhale's API

How _does_ FW order results? Is there, like, any logic?

> Any thought?

Simple but clear :+1:

**Comment by apognu** [comment]
> How does FW order results? Is there, like, any logic?

From what I can gather from the output of the API, it _seems_ to desc-sorted with the internal numeric ID of the item.

**Comment by apognu** [comment]
Mmm, we do have the same "issue" with playlists, radios and favorites. For now, I'll sort them by name to have something cohesive, but maybe another strategy could be better for one of those.

**Comment by keunes** [comment]
> Mmm, we do have the same "issue" with playlists, radios and favorites. For now, I'll sort them by name to have something cohesive, but maybe another strategy could be better for one of those.

If these are also returned in order of their ID, and this ID is incremental based on creation date, they are ordered in a way that is somewhat logical. As in: your most recently marked favourites and latest created playlists and radios on top would make sense to me.

I'm just thinking whether this order of delivery shouldn't be dealt with upstream, on a FW API level. Any other client would possibly have the same issue.

**Comment by georgkrause** [comment]
@keunes As far as I know the funkwhale API has an ordering option, you can pick in which order you will receive the list. So its already handled upstream ;)

**Comment by apognu** [comment]
Yes, that's what I'm using now, the `ordering` API parameter (I couldn't sort locally even if I wanted to because Funwhale only gives items 50 at a time).

**Comment by apognu** [comment]
@keunes The initial issue stating that long lists would make it hard to find one specific item, hence the alphabetical order, which is, I believe, quite a natural search mechanism.

Remembering that a playlist called "Alternative" is a the end of a 30-item list because it was the first you ever created seems like a stretch to me.

Anyway, I am open to discussion, and this could still be changed in a future release. Alphabetical will still be part of the next update until a consensus can be reached. :)

**Comment by MightyCreak** [comment]
> Any thought?
I think alphabetical order should be the default sorting option since, as you said, it's the natural order any user is expecting.

As for the other sorting orders, I completely agree that if the information is not displayed, it makes it clunky for the user to know what's happening. So I think displaying the album year is a good thing. But also, I think it would be nice to show the sorting order on the UI as well.

Here's a sketch of what I have in mind:
![86911739-51d5f980-c10b-11ea-8f0e-96f9edb26439](https://user-images.githubusercontent.com/6382548/89127004-336bdf80-d4b8-11ea-934c-a89b20c933cf.jpg)

As for the ordering API, I guess you found it, but here's the Swagger link, just in case :wink: 
https://docs.funkwhale.audio/swagger/#/Library_and_metadata/get_api_v1_albums_
