### ISSUE TITLE
Host name error: IllegalStateException

### ISSUE THREAD

**Issue by Houndie** [apognu/otter#62]
When attempting to log in to otter, I get the following error displayed beneath the Host Name field:

```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 1 path $
```

**Comment by dregin** [comment]
Related to Cloudflare's outage?

**Comment by Houndie** [comment]
No, it's a locally hosted instance.

That said, I backed out and am now having trouble logging into the web interface, so this might actually not be an otter problem.  I'm going to close this and if it persists reopen again later.

**Comment by Houndie** [comment]
Just an update for anyone that finds this, I ran into this issue on the server: https://governance.funkwhale.audio/d/lQuKDY19/ldap-auth-and-db-error-at-second-login

The fix in that thread also worked for me.

**Comment by apognu** [comment]
I'm glad the issue is not coming from Otter and hope you'll get whatever the issue is fixed.

But I also see that we may have another tweak to do on the error messages on login. Presumably, the issue you're facing is Funkwhale not sending back proper JSON or some schema we do not expect.

I'll note to check how to make this a bit more user friendly.
