### ISSUE TITLE
Can't Connect To Instances

### ISSUE THREAD

**Issue by grravity** [apognu/otter#64]
I have tried open.audio and tanukitunes.com and can't connect to either (failed to connect error)

I tried enabling allow HTTP and both enabled and disabled anonymous authentication. Note I'm not trying to login, just listen as guest which they allow and work on their sites, but I cannot connect through Otter. 

Android 10, Otter 10.0.20

**Comment by Razgriz375** [comment]
I was able to connect to tanukitunes.com with anonymous access but it would force close the app when trying to load the library. This is on the most recent debug release. 1.0.20-56-f062e62-develop

**Comment by apognu** [comment]
As far as the first issue (failed to connect) is concerned, I do not really have a clue here. Failed to connect without any detail, especially when connecting anonymously, is usually due to network issues. :/

We do have two blocking issues with instances (like open.audio or tanukitunes.com) that use the development version of Funkwhale, namely:
 * the `/users/users/me` endpoint was renamed to `/users/me`, which could present a "could not retrieve information about your user" error message.
 * the schema used to retrieve cover arts was also changed, which definitely introduce the crash in @Razgriz375 comment (still waiting for upstream confirmation this is the same situation).

We are in a bit of a predicament here, since I cannot reasonnably only support instances on the bleeding-edge version of Funkwhale. On the other hand, those instances seem to be really popular, so that would prevent a large potion of users from using Otter.

Otter does not have a way to change behavior depending on Funkwhale version, and even if it did, it could quickly become unmanageable if every commit had to be vetted for breaking changes.

**Comment by apognu** [comment]
The crash reported by @Razgriz375 should be fixed in the latest `develop` version.

An [issue](https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1184) was created on Funkwhale's issue tracker to request backward compatibility regarding the userinfo endpoint.

@grravity Do you still have the exact issue you posted?

**Comment by keunes** [comment]
On a side note: given that both Funkwhale and Otter are relatively young, I think it's only fair & to be expected stuff breaks because elements get deprecated. After FW v1 lands I guess that'll change.

**Comment by grravity** [comment]
I'm stupid, I just noticed Netguard was blocking Otter. It seems to be connecting now, although it looks like others may have issues? Up to you whether you want to close the issue. Sorry for wasting any time.
