### ISSUE TITLE
Add Widget

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [apognu/otter#69]
Hey there,
First, thanks for your great work. I'm just getting started with Funkwhale and this Otter app is really promising, and already daily usable!

Just one more feature request : any chance to see a good old 4x1 widget to add on the homescreen ? I've no idea how hard it is to make.

Cheers !

**Comment by apognu** [comment]
I do not use widgets on a day to day basis, and I _personally_ do not really see the point when all media controls and information should be available both in the notification panel and the lock screen.

I never created widgets for any app but, as far as I know, it should not be that complicated, though I would prefer to keep my focus on the main app which, as you said, still has ways to go, rather than dedicating my resources on a feature I would not use (both in terms of development burden and maintenance surface).

This _may_ be reconsidered once the app is considered finished, but I will not commit to this until then.

**Comment by GuillaumeLeGoc** [comment]
Okay I totally understand that from _you_. The same arguments were used by Spotify where updates after updates the app loses in functionnality to get a perfect copy of the app from iOS. From them the argument was not relevant, but it is from you. In my personal case, I use my device single-handed and scrolling to get the notification panel is not really comfortable and when I unlock the screen basically I end up on home because of fingerprints, hence the widget utility for me.
Anyway, keep up the good work mate !

**Comment by DanielNautre** [comment]
@GuillaumeLeGoc You should be able to find a generic widget for android media controls that would work with Otter (as well as most media app)
Zooper, UCCW, and other similar widget handle this by default
Disclaimer: I have not actually tested this.
