### ISSUE TITLE
Add preference for 'add to' or 'replace' queue when hitting play button

### ISSUE THREAD

**Issue by keunes** [apognu/otter#75]
As per https://github.com/apognu/otter/issues/65#issuecomment-670966548

Currently initiating playback adds items to the queue, if I'm not mistaken. This is the Funkwhale default pattern. However, I find FW's approach of 'adding to' rather than 'replacing' the queue quite confusing/annoying, and would be happy to have Otter behave differently.

Next to 'Add to queue', an alternative pattern would be 'Replace queue'. I would like to request the introduction of a setting that regulates Otter's behaviour in this regard. That keeps the main UI clean while allowing users to follow their preferred pattern (Funkwhale or Spotify).

I imagine single person would either prefer 'add to' or 'replace' queue (and stick to this preference) – warranting an app-wide setting. (This, contrary to playing 'shuffle' or 'in order', which is much more likely to both be used by a single person depending on their mood and the album/list they're listening to).

**Comment by apognu** [comment]
Just so we're clear, right now, Otter's default main action (big blue button) is always to replace the queue. Same thing when tapping directly on a track. Blue buttons replace the queue with the current context. And there are overflow menus with "additive" equivalent ("Add to queue" or "Play next").

So from my point of view, Otter already behaves the way you would prefer. If it's not, it's a bug, because that's my preference as well.

**Comment by keunes** [comment]
Ok, this is embarrassing. From other discussions I was under the impression that Otter followed Funkwhale, but I finally just installed a Prod FW instance but not uploaded any music yet. So it was based on pure theory not tests. I'm so sorry. Should I close it? Behaviour as you describe it sounds perfect.

**Comment by apognu** [comment]
No worry, there had been a lot of ideas floating around. ;)

Current behavior is perfect for me as well. So we'll keep it that way until someone else raises the issue.
