### ISSUE TITLE
Missing Artwork 

### ISSUE THREAD

**Issue by screwfaze** [apognu/otter#78]
I seem to be missing all the album artwork on otter that is showing just fine on web browser. I am using funkwhale with reverse proxy nginx any suggestions welcome.

Thanks

**Comment by apognu** [comment]
Does the issue persist when you force a refresh of the list (by pulling to refresh)?

Which version of Otter and Funkwhale?

**Comment by ellienieuwdorp** [comment]
I was having similar issues due to running the funkwhale (all-in-one) docker image behind an nginx reverse proxy that handles SSL. The docker image would use the http url instead of https for most images causing them to not appear.

I've found some workarounds by editing the nginx config in the container but eventually stumbled upon the undocumented `FUNKWHALE_PROTOCOL=https` env variable in the all-in-one docker image which fixed all my problems related to this.

**Comment by apognu** [comment]
I actually had the exact same issue at first with my custom ARM docker image for Funkwhale. Glad you could sort this out.
