### ISSUE TITLE
Save queue in a playlist

### ISSUE THREAD

**Issue by apognu** [apognu/otter#81]
Now that the queue has actions associated to it and we have basic playlist management worked out, we might want to add the option to save all tracks in the queue in a new or existing playlist.

I don't have access to Funkwhale right now, but I seem to remember seeing something like this.

**Comment by AMoonRabbit** [comment]
Funkwhale doesn't have a "save current queue to playlist" from the queue, but you can manually create a new playlist, and from the playlist editing tools import the current queue. 

But yes, this would be a good feature to have but wonder if, because it will only save what has been generated in the radio, whether you can have these saved playlists then continue to act as a radio once the saved list reaches the end?

**Comment by apognu** [comment]
Well I, for one, save playlists not only from radios but from different sources: manual adds, radios or simply luck ("hey I like the flow I had in this session, I'd like to have it again"). And playlists can contain tracks that we initially played from different sources.

I don't think we can assume a playlist should continue playing as a radio when it's finished. And I'm not sure we should. A playlist, in my mind, should be a self-contained user-defined list of tracks, and allowing it to play something outside the playlist without user action would be weird.

Finally, since Funkwhale does not have something like this (as far as I know), those would be stored in local storage and not persisted.
